# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-23 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_a',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
